### ISSUE TITLE
Splitting spider logs

### ISSUE THREAD

**Issue by oltarasenko** [oltarasenko/crawly#101]
One of the concerns I want to address in the new milestone is Logs. 
We need to be able to split logs per spider if requested. It would allow us to have spider logs in one place. Understanding the performance of the job, and what was dropped for example, etc.

As I see it should be quite similar to: https://docs.scrapy.org/en/latest/topics/logging.html

@Ziinc I wonder if you have solved this problem on your own already or have some ideas to share?

**Comment by Ziinc** [comment]
Right now my crawler logs are getting swallowed up into the void  and mixed with application logs.

from my understanding, Logger can be configured to with additional backends.
There's a file backend package here: https://github.com/onkel-dirtus/logger_file_backend
Log rotation isn't included, though.


It would be interesting to log realtime errors to the web ui like how the new phoenix liveview admin request logging does.

**Comment by Ziinc** [comment]
@oltarasenko the simplest method to do this would be to use [Logger's metadata](https://hexdocs.pm/logger/Logger.html#module-metadata) to specify spider name and job ids (#102 ) , and allow the user to filter the logs with the [logger file backend](https://github.com/onkel-dirtus/logger_file_backend).

It keeps Crawly's scope limited, while we can bless the logger backend filtering method as recommend way for spider logging.
