### ISSUE TITLE
Tag jobs with unique id

### ISSUE THREAD

**Issue by oltarasenko** [oltarasenko/crawly#102]
One of the common problems I am facing right now, if that it's not possible to separate one crawly's job from another, from the external point of view. 

E.g. the same spider can be executed multiple times. How do we know that the data came exactly from a given run? For example here: http://18.216.221.122/ in order to group items inside a UI we need to have an ID to unite them.

I plan to:
1. Extend engine in the way that start_spider would accept an optional job_id parameter
2. The engine would automatically generate the job if now provided
3. Crawly will use this job_id when the communication with the external world is done. E.g. if we are shipping logs somewhere -> it will be used. If we're shipping items it will be used.

What do you think about the idea?

**Comment by Ziinc** [comment]
It is feasible and logical to have it. I think using the term crawl would be better.i.e. Giving each crawl attempt an id. Job could refer to many things. 

Could be used for the WriteToFile filename too, instead of timestamps. 

A simple id could be a 13 digit Unix timestamp. I don't think uuids are needed.

**Comment by oltarasenko** [comment]
I like the idea of `crawl_id`.

Otherwise, I don't see why should not we have it as UUID? E.g. uuid is already in our list of deps. So it's not like we have to add something in order to have it.

**Comment by kaozdl** [comment]
I could work on this

**Comment by Ziinc** [comment]
@kaozdl I think @oltarasenko merged in the PR for this issue last week. 

@oltarasenko if there's no other changes necessary then we can close this issue

**Comment by oltarasenko** [comment]
Yes, sorry I forgot to update the ticket :(
