### ISSUE TITLE
Spider scheduling for continuous crawling 

### ISSUE THREAD

**Issue by Ziinc** [oltarasenko/crawly#109]
I'm looking to do cron-style spider scheduling, where the engine starts the spider if it is not running at a scheduled timing interval. 

Should this be within the Engine or Commander (?) module context?

This would require the Engine to be part of a supervision tree, I think.

**Comment by oltarasenko** [comment]
What about using cron to schedule the run through the HTTP API? 

Otherwise, I am using https://github.com/quantum-elixir/quantum-core for crawly_ui.

**Comment by Ziinc** [comment]
Yea i was looking at quantum-core as well. I was wondering if this functionality should be in-built, or is it out of scope.

I prefer to keep everything self-contained, hence not actually using cron.

**Comment by Ziinc** [comment]
Will handle this outside of crawly
