### ISSUE TITLE
Pattern for handling authentication of requests

### ISSUE THREAD

**Issue by bapti** [oltarasenko/crawly#124]
Hi,

I'm interested in know what the appropriate pattern is for authenticating a spider? Most of the spiders I'm writing need to log in first before being able to scrape the content that I need access to. What would be the normal pattern for this as I've not found any examples of it that I can see.

My guess would be to write a middleware to perform the log in and set the auth cookies, however this will be a different authentication process for the various different spiders. Would this be done within the spider itself perhaps in the `init()` function?

Thanks for any help.

**Comment by Ziinc** [comment]
You can write a middleware that takes in auth options and sets the cookies, and then set it on the `override_settings` callback.  This lets you parameterize your auth settings based on spider. The `init/0` callback is more for starting request links.

**Comment by oltarasenko** [comment]
@bapti yes, I agree, we clearly miss an example here. Btw, what are you trying to crawl? Maybe we could try it as an example.

**Comment by oltarasenko** [comment]
@bapti I want to let you know that I am working on the case. Have already solved the basic login, now trying to generalize it. Will present steps soon!

**Comment by oltarasenko** [comment]
@bapti I will write an article with a detailed explanation soon. For now please use this as an example: https://github.com/oltarasenko/crawly_login_example

Please let me know if you have any questions! Would appreciate a feedback!

**Comment by bapti** [comment]
@oltarasenko thank you for all this, I look forward to the article.

The site I was trying to crawl has some fancy javascript fingerprinting (I'm assuming to prevent scraping), I tried a few things to get things to work and couldn't. In the end I had a quick go using puppeteer to see if I could perform the login through it, and that worked which kind of proved to me that I needed a full browser environment for that particular site.

But even so, thanks for the example, it looks like the right way to go for most instances

**Comment by oltarasenko** [comment]
Ok, @bapti 

Thanks for the feedback. Yes, it might be the case. I think we should put more efforts toward supporting puppeteer
backend.

In any case, if you have a way to share the website name, I can test it myself to see what can be done. I have spent quite a bit of time debugging bans in the past, so maybe this experience could help.

If you don't want to share the site here, you can do it via email, or elixirforum (I have an account there). Let me know!

**Comment by oltarasenko** [comment]
@bapti the article is finally published now, and can be available via https://oltarasenko.medium.com/web-scraping-with-elixir-and-crawly-extracting-data-behind-authentication-a52584e9cf13
