### ISSUE TITLE
How to wait for running spiders to finish?

### ISSUE THREAD

**Issue by phortx** [oltarasenko/crawly#153]
I'm writing a CLI tool which uses a spider. Seems like the process ends bevor the spider is finished. How can I wait for the spider to be finished and print a success message?

**Comment by phortx** [comment]
I'm starting the spiders via

```elixir
Crawly.Engine.start_spider(Spider)
```

**Comment by oltarasenko** [comment]
Hey @phortx!

You could define on_spider_closed callback function (https://hexdocs.pm/crawly/0.12.0/configuration.html#on_spider_closed_callback-function) which would notify your process.

**Comment by phortx** [comment]
Hi @oltarasenko 

thanks for your response. However, this solution seems not to be very elegant. Isn't there a way to link the process to a supervisor or use Tasks for that ?

**Comment by oltarasenko** [comment]
Unfortunately, right now we're not returning a PID of the related manager on start, we could do it in the future. However for now the closes solution I see is to use the: https://github.com/oltarasenko/crawly/blob/master/lib/crawly/engine.ex#L66

**Comment by phortx** [comment]
Thanks for the advice! 

Do you have a hint how I could use that? I'm rather new to elixir and not sure what to do with the manger right now 😄

**Comment by oltarasenko** [comment]
The manager is probably the main process related to a spider. E.g. it starts all other relevant processes, which form the spider itself. Also, the manager is linked to workers or storages. Probably you can try to put a link on it if you want.

**Comment by phortx** [comment]
I'll try it, thanks!

**Comment by phortx** [comment]
Ok, this is even more complicated because the spider doesn't finish when the quque is empty ... is there a way to let a spider stop when the work is done?

**Comment by oltarasenko** [comment]
@phortx Spider should finish when the queue is empty. However, it waits a bit of time before doing so, which is controlled via https://hexdocs.pm/crawly/0.12.0/configuration.html#closespider_timeout-pos_integer

**Comment by phortx** [comment]
Thanks for the fast response :) 

I wasn't able to get the supervising running, so my current solution is an endless loop which waits a second and then checks `Crawly.Engine.running_spiders()` which works well.

However the spider didn't disappear from the Map which is returned by `running_spiders` after the work is done.

Setting `closespider_timeout` solved the issue. Thanks for your help!
