### ISSUE TITLE
Move away from using global app env for pipeline module config

### ISSUE THREAD

**Issue by Ziinc** [oltarasenko/crawly#22]
Pipeline config should be localized to the specific pipeline. 
Benefits:
1. Reduces clashes (when more middlewares/pipelines get built)
2. makes parameter declaration clearer
3. makes pipelines more "functional" and reusable
4. use of `Application.get_env` usage within pipeline modules makes things less clear when declaring pipelines.

Related to #20 , would pave the way for adding logic into a pipeline (instead of having a fat pipeline module)

Proposed api:
- Tuple definitions would only be required for modules that require configuration
    - at the pipeline level, they could throw an error when checking for parameters, or use default values.
- a pipeline module can also be passed directly when no parameters are needed

For example:
```elixir
pipelines: [
  ....
  MyCustom.Pipeline.CleanItem,
  {Crawly.Pipelines.Validate, item: [:title, :url] },
  {Crawly.Pipelines.DuplicatesFilter, item_id: :title },
  Crawly.Pipelines.JSONEncoder
]
```
Besides adjusting existing built-in pipelines, this proposed change would also require the adjustment of `Crawly.Utils.pipe` to check for tuple definitions.

**Comment by oltarasenko** [comment]
I kind of like this idea!

**Comment by Ziinc** [comment]
I'll open a PR for this over the weekend
