### ISSUE TITLE
Retries support

### ISSUE THREAD

**Issue by oltarasenko** [oltarasenko/crawly#26]
We need to be able to re-try failing requests.

**Comment by Ziinc** [comment]
can be implemented as a middleware. failed requests then go back to the start of the middleware pipeline, then get dropped if the retry count reaches threshold

**Comment by oltarasenko** [comment]
It might be a bit more complex, as middlewares are purely functional by design.

We might add attempts field to a request structure. And then to have the Retries middleware which cuts items with large amount of retries. 

However it's worker who knows if the request have failed or not at the end of the day.

**Comment by Ziinc** [comment]
Closing, with #47 merged
