### ISSUE TITLE
Add options for HTTPoison

### ISSUE THREAD

**Issue by srmor03** [oltarasenko/crawly#33]
How it is possible to implement in Crawly adding options for HTTPoison.
For example, such:

```

url = "https://example.com/api/endpoint_that_needs_a_bearer_token"
headers = []
**options = [ssl: [{:versions, [:'tlsv1.2']}], recv_timeout: 500]**
{:ok, response} = HTTPoison.get(url, headers, **options**)
```

And so that it can then be used in a spider.

**Comment by Ziinc** [comment]
You want to do it on a per-request, per-spider, or global basis?

**Comment by srmor03** [comment]
Global basis

**Comment by oltarasenko** [comment]
I agree. I need to add it. I will schedule the change for the next release.

**Comment by oltarasenko** [comment]
@srmor03 I have made the following change to address your issue: https://github.com/oltarasenko/crawly/pull/38. Hopefully, it can be reviewed and approved soon!

**Comment by Ziinc** [comment]
The HTTPoison options for ssl can be set through a custom request middleware. Configuration and secrets can be passed through Application.get_env in your config.exs.

Please refer to the latest documentation in master:

https://github.com/oltarasenko/crawly/blob/master/documentation/basic_concepts.md#request-middleware-example---add-a-proxy

The latest documentation is not up yet on hex.pm,so refer to the markdown file for now. For v0.7.0 and below, tuple based middleware/pipeline declarations are not available.

Closing.
