### ISSUE TITLE
Implement Crawly.crawl/2 command for fetching given page with given spider

### ISSUE THREAD

**Issue by oltarasenko** [oltarasenko/crawly#52]
It may be Crawly.crawl(url, spider_name) or Crawly.crawl_with(url, spider_name)

The idea is based on: 
https://github.com/oltarasenko/crawly/pull/51#issuecomment-573744130

We want to build a way to debug how spider would fetch a given page. Which links are going to be extracted? Which items are going to be fetched?

**Comment by Ziinc** [comment]
Perhaps instead of having a completely separate function, we can extend the fetch function to have a :with option for passing in the spider?
