### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by cpursley** [oltarasenko/crawly#7]
This looks like a very useful project.

Can you please update the example Crawly Example (https://www.homebase.co.uk) and Tutorial? They both seem to be broken.

**Comment by oltarasenko** [comment]
@cpursley I have checked the example. And added the following link to the readme: https://github.com/oltarasenko/products-advisor

Hopefully, it could help to start with Crawly! Please let me know if you need more help setting things up for your case!

**Comment by cpursley** [comment]
Дякую (или Спасибо)!

**Comment by oltarasenko** [comment]
Happy to help you! Please let me know if you need to help bootstrapping the project you're working on
