### ISSUE TITLE
Ecto item pipeline configuration

### ISSUE THREAD

**Issue by Unumus** [oltarasenko/crawly#70]
I have a problem with build the custom Ecto pipeline.
https://hexdocs.pm/crawly/basic_concepts.html#custom-item-pipelines

If I get it right, I need to define the pipeline module in my config.exs file to` pipelines:[] `section? 
Also I miss understanding that does mean this part `MyApp.insert_with_ecto(item)` ? Do you mean Repo.insert here or what?
Can you please describe in more detail how should I connect it?

P.S. I apologize if the questions seemed stupid, but I still do not understand how this works. I will be thrilled when I figure it out. Ecto is a missed puzzle for my crawly projects.

**Comment by Ziinc** [comment]
For example, if you're combining it with an existing elixir app, your app would probably be organize by contexts. This `insert_with_ecto` function would then be a function within your app context. Your context would then do the changeset validation and perform the insert.

You could do a direct Repo.insert, depends on your integration context.

Are you trying to integrate into an existing app, or to create a standalone crawler with its own ecto repo? Either way, the contexts organisation would still be the same

**Comment by Unumus** [comment]
@Ziinc Thanks all works perfectly. It is was pretty simple :)

In the documentation, the Ecto example part, as I think, lacks one piece.  It is too necessary to update the pipelines in the crawly.config file.
