### ISSUE TITLE
Example for CSV export

### ISSUE THREAD

**Issue by cpursley** [oltarasenko/crawly#8]
I see that you can export JSON with the following config:

```
  config :crawly,
    other configs...
    pipelines: [Crawly.Pipelines.JSONEncoder]
```

Is there a middleware for exporting to CSV format or a recommend way to do this?

Also, why does the file format end in `file.ji` instead of `file.json` when using JSONncoder?

**Comment by oltarasenko** [comment]
Hi @cpursley,

The CSV exporter middleware is not yet developed. I plan to add it to Crawly very soon. Will update this ticket once it's added!

**Comment by oltarasenko** [comment]
@cpursley I have now added an example of CSV Encoder here: https://github.com/oltarasenko/crawly-cars

**Comment by cpursley** [comment]
Thanks!
