### ISSUE TITLE
How to use Crawly when not need to collect links?

### ISSUE THREAD

**Issue by Unumus** [oltarasenko/crawly#80]
I have in Database about 250k URLs that need to enrich. Go to every link of the list and parse its HTML. Is there a good way how to feed them to Crawly queue? Is it suitable to use Crawly in this case?

**Comment by Ziinc** [comment]
I've faced this issue as well. My temporary solution is have a database query in the `init` callback that fetches the urls and passes it in as a list.

My only main concern is that the size of the list could be memory-intensive, and for large amounts it would be better to use a Stream instead to let the worker iterate over it indefinitely.

**Comment by Unumus** [comment]
@Ziinc I did try it too, however did not found that to put instead of requests in %Crawly.ParsedItem{}?

**Comment by Ziinc** [comment]
@Unumus You don't have to return new requests in this case. If you load up all the urls that you want to hit at the Spider.Init, then you don't need to add on new urls (unless you are inserting new ones)

**Comment by oltarasenko** [comment]
@Ziinc @Unumus I was using Crawly for the task of URLs monitoring as well. In general, my observations is the following: 
1. The main concern is parse_item. You should be able to extract data out of the URLs (especially if we're talking about a large list of sites
2. You could disable the Domain Filter middleware to extract data from multiple sources
3. As was mentioned by @Ziinc the init is not the best place to supply all the URLs, due to the memory limitations (as you're going to overflood the RequestsStorage, on the other hand, it should be quite capable to store up to million requests there). I was adding a DB query to parse_item instead, slowly feeding the DataStorage (so workers from the other hand will have time to clean it up as well).

**Comment by Unumus** [comment]
@Ziinc I use Proxy pool. Will in that case be done isolated request from a new IPs or not? Just seems that in my case requests go from the same IP.

**Comment by Ziinc** [comment]
> @Ziinc I use Proxy pool. Will in that case be done isolated request from a new IPs or not? Just seems that in my case requests go from the same IP.

If you load it up through the init, the requests generated should pass through the middlewares declared. It depends on how you are assigning proxies from your pool. If it's through the middleware, it shouldn't be an issue

**Comment by Ziinc** [comment]
@oltarasenko perhaps we could init the spider with a stream, then the worker maintains maybe 1000 requests in the RequestsStorage by popping off more urls from the stream as requests get fetched?

**Comment by oltarasenko** [comment]
@Ziinc init is a simple way of starting with something, now it just sends the request to request storage. Having a stream instead would require us to build a complicated logic there. Again what is the problem of reading the stream from the `parse_item/1` instead of `init/0`?

**Comment by Unumus** [comment]
@Ziinc yes I use the middleware however, each worker always operate on the same IP, and its IP do not changes during runtime.

**Comment by Ziinc** [comment]
@oltarasenko I'm wary of placing any database logic in `parse_item/1`, as it would mean tens or hundreds of thousands of unnecessary queries against the database. This multiplies the more spiders there are that are running concurrently.

Maybe a good approach would be to leverage the new callback api to "inject" requests into the RequestsStorage? If a callback receives the RequestsStorage state, the logic for doing the database query can live in the callback, outside of `init/0` and `parse_item/1`. We could then send a message to the RequestStorage worker to add X requests into the queue

**Comment by oltarasenko** [comment]
@Ziinc But in this case, it should be also possible to have an intermediate process that makes queries. So the `parse_item/1` does something like <cache>.get() or <cache>.fetch(). It would not only allow limiting the number of queries to the database, but also would allow solving the problem of processing each entry once only.

Conceptually I think it's a job of parse_item to fill the requests storage. Should It be capable of retrieving items in some other magical way? At this point, it does not seem to be the case, I still think you can achieve the results with parse_item.

Side note:
When I was creating the original design of Crawly I was also calculating situations when we have different Requests/Items storages. As soon as they share the same interface. Probably we can resurrect this idea at some point. But maybe please try to see, if you can solve your problem without it.

**Comment by Ziinc** [comment]
>  It would not only allow limiting the number of queries to the database

Which is why i suggested to @Unumus to do it in the `init`, because there isn't a way to limit the number of queries to the db if inserting through `parse_item/1`. Having access to the RequestsStorage state might help with adding limit logic in  `parse_item/1`. 

I don't really think this is all that important, it is more of a "quality of life" or "spider management" issue, more for #37

**Comment by Unumus** [comment]
Proxy works now as accepted. 

But have a new issue, about that approach. Spider work 1-2min perfectly, and after that just stoped. Can it be stoped because of items not coming into pipeline?

```
[info] Current crawl speed is: 0 items/min
[info] Stopping Scraper, itemcount timeout achieved
```


```
config :crawly,
  retry: [
    retry_codes: [400, 500],
    max_retries: 3,
    ignored_middlewares: [Crawly.Middlewares.UniqueRequest]
  ],
  concurrent_requests_per_domain: 7,
  # follow_redirects: true,
  middlewares: [
    Crawly.Middlewares.UserAgent
  ],
  user_agents: [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41"
  ],
  pipelines: [
    # {Crawly.Pipelines.Validate, fields: [:id, :title, :url, :price]},
    # {Crawly.Pipelines.DuplicatesFilter, item_id: :id},
    # {Crawly.Pipelines.JSONEncoder, []},
    # {Crawly.Pipelines.WriteToFile, extension: "jl", folder: "/tmp"}
  ]
```

**Comment by oltarasenko** [comment]
@Unumus your spider is not extracting items. Thats the reason why its stopped. See also: https://hexdocs.pm/crawly/configuration.html#closespider_timeout-pos_integer

**Comment by Unumus** [comment]
@oltarasenko I already tried a different settings of closespider_timeout and itemcount. 
The behaviour is same. What is in your opinion should I indicate there?

```
  closespider_itemcount: 1_000_000,
  closespider_timeout: nil ,
```

**Comment by Unumus** [comment]
I see, changes nil to 0 and seems it is not stop more. It seems to me a not intuitive. Because of in documentation saids that default is nil - and seems that if this is nil then the crawler will not be stoped by default.

**Comment by oltarasenko** [comment]
@Unumus the new version should improve the intuitivity of the setting. From my point of view, the closespider_timeout  should never be nil, as it would mean that the crawling process will run forever. Try setting it to low numbers like 2-4 (e.g. it should extract at least 2 items per minute).

Note: Your crawler is not extracting items, that's the reason of stop. E.g. please check the parse_item function to see if it extracts items properly.

**Comment by Unumus** [comment]
@oltarasenko I do not use pipelines, I insert the data directly to my Postgres. The question is concerned with that issue "How to use Crawly when not need to collect links?".

 So the items per minute are always = 0. Everything works fine now. Happy.

**Comment by oltarasenko** [comment]
@Unumus are you inserting the data directly from the parse_item, without returning items, right? (Otherwise, items are being counted by the ItemsStorage process, which stands at the end of all pipelines e.g. parse_item -> pipeline1 -> pipelineN -> storage, if you don't have pipelines enabled it goes like parse_item -> items_storage).

However, I am happy to know that it works.

**Comment by Ziinc** [comment]
Insert data in a custom pipeline, not in the parse_items callback.

**Comment by Unumus** [comment]
@oltarasenko in parse_item I return a "fake" map like that `%{item: response.body}` because otherwise Crawly complains, and above that map I send the scraped data into Ecto module. 

Did not see any problem with performance right now. Only that code looks not clear enough.  But I did not tried yet put into the queue list with more than 250k records.

**Comment by oltarasenko** [comment]
@Unumus technically you should return a https://github.com/oltarasenko/crawly/blob/master/lib/crawly/parsed_item.ex from the `parse_item/1`.

**Comment by Unumus** [comment]
@oltrasenko yes I know just in that case I do not need it, so I decide just return a map, because of I do not need the request parameter, but the datastruct required it. And if I not wrong I got some errors when put some fake data such as empty lists and so on, into %Crawly.ParsedItem{}.
Need some other solution. To be possible to use Crawly engine.

**Comment by oltarasenko** [comment]
Sorry, and what do you get if something like `%Crawly.ParsedItem{requests=[], items=[my_items_list]}` is returned? You don't really need to add new links or items from the parse_item. You can actually return just `%Crawly.ParsedItem{requests=[], items=[]}` if you want

**Comment by Unumus** [comment]
@oltarasenko sorry, %Crawly.ParsedItem{requests: [], items: []} works now. Thanks, it looks better now.

**Comment by oltarasenko** [comment]
You could even fake it a bit more with something like %Crawly.ParsedItem{requests: [], items: [:fake_item]}, so crawly will still get items from every request. However, I think you should do what @Ziinc is advising...

**Comment by Unumus** [comment]
@oltarasenko Thanks! I will try to do it with custom pipeline.

**Comment by Unumus** [comment]
@oltarasenko it will be advantageous if we can add an option in init() callback, to provide a state if it required, into parse_item. 

`[start_urls: urls, state: state] = spider_name.init()`

**Comment by oltarasenko** [comment]
Sorry, could you explain more? Can we do it in a separate topic if it's not related?

**Comment by Unumus** [comment]
@oltarasenko  I have a pipeline which I wrote in the first post of that issue.

I put the list of URLs to init(). The source of the links is Postgres.

Notable is that the initial table holds some state which needs to share with the new spider(such us ID to build association).  

I need a way to get that data in the `parse_item/1`. I think it will be useful if it will become `parse_Item/2 ` instead, where the second parameter will be an arbitrary state.

**Comment by Ziinc** [comment]
In the pipeline, why can't you query on your url and update the records that match? If the urls already act as a primary key, it makes the state passing just to have the id a bit redundant. 

Also, passing the arbitrary state around is like playing hot potato where you don't really know what is in the potato. Error prone and not very efficient.

**Comment by Unumus** [comment]
@Ziinc  

The parent table do not contain the link. I generate this link from the company name. 

However do not found a good reason why do not extract that company name from the link and build association. Thanks!

**Comment by Unumus** [comment]
Moreover I found that can put parent id in UTM.

**Comment by oltarasenko** [comment]
I am closing this one. I think it's resolved now. Please reopen if you think it's not the case
