### ISSUE TITLE
How can I connect Proxy to Splash?

### ISSUE THREAD

**Issue by Unumus** [oltarasenko/crawly#81]
Is there an option to add a proxy in Splash from Crawly?

**Comment by oltarasenko** [comment]
As soon as requests are executed by splash, the proxy needs to be configured there. Please see: https://splash.readthedocs.io/en/stable/api.html#proxy-profiles

**Comment by Ziinc** [comment]
Note that you can provide the proxy option as a query string on a per-request basis.

https://splash.readthedocs.io/en/stable/api.html

This involves setting the `proxy` option on Splash fetcher declaration.

The options are passed as query_params to the Splash HTTP api.

https://github.com/oltarasenko/crawly/blob/deb06c31bb2982bd27a2dace1953a03f2bfbe33d/lib/crawly/fetchers/splash.ex#L45
