### ISSUE TITLE
Why Crawly do not use Poolboy library?

### ISSUE THREAD

**Issue by Unumus** [oltarasenko/crawly#82]
It might look a little offtopic. This question interesting for me in in terms of my education.

Is there some reason why Crawly do not use Poolboy library?

**Comment by oltarasenko** [comment]
Hi @Unumus 

It's a bit offtopic indeed. I was using Poolboy on a couple of projects, and I would confirm that this is a solid library. However, due to the fact that Crawly is built on the top of queues and pools, I decided to make something more flexible and suitable for my needs.
