### ISSUE TITLE
Docs for configuring Splash Fetcher should be base_url not base_splash_url

### ISSUE THREAD

**Issue by rnice01** [oltarasenko/crawly#84]
Docs for Basic Concepts and configuring Splash fetcher state the configuration should be
`fetcher: {Crawly.Fetchers.Splash, [base_splash_url: "http://localhost:8050/render.html"]}`

However, the fetch method is looking for the `base_url` keyword in the config. As seen [here](https://github.com/oltarasenko/crawly/blob/407fa8e6beddf1ff831334672898f1f37785b720/lib/crawly/fetchers/splash.ex#L32)

The message for the error, [here](https://github.com/oltarasenko/crawly/blob/407fa8e6beddf1ff831334672898f1f37785b720/lib/crawly/fetchers/splash.ex#L35), should be updated too.

**Comment by Ziinc** [comment]
It seems like there a lot of documentation errors. I'll do up a PR to consolidate efforts from #85 as well.

**Comment by oltarasenko** [comment]
This is done now!
