### ISSUE TITLE
Announcement: Crawly UI, first early prototype

### ISSUE THREAD

**Issue by oltarasenko** [oltarasenko/crawly#89]
Hey people,

I have spent quite a bit of time prototyping a UI for Crawly. I think it's the next step we have to make in order to make Crawly visible in the Elixir and Web crawling space.

A good UI would help to convert web scraping into a process with clear create - test - use circles. Please have a glance on the early prototype here: 
https://github.com/oltarasenko/crawly_ui

or test it here: http://18.216.221.122/jobs/1/items/

**Comment by Ziinc** [comment]
Really dig the new logo. The ui looks great, though i notice that its not responsive on mobile yet.

**Comment by oltarasenko** [comment]
@Ziinc Well, maybe walmart is a bad example. It has banned Crawly, without proxies it's a complex target. I am looking for a more simple but large site to showcase it

**Comment by Ziinc** [comment]
I think it is because there isn't rate limiting. It was scraping fine when I tried it.

Their anomaly detection probably kicks in due to the high hit rate.

**Comment by oltarasenko** [comment]
Yes it works atm. The crawl speed is quite low. Only 2 concurrent
connections.

**Comment by oltarasenko** [comment]
Ok, now we have a PR. I will close this ticket now
