### ISSUE TITLE
WriteFile folder option improvements

### ISSUE THREAD

**Issue by Vesuvium** [oltarasenko/crawly#91]
Hi everyone! I've been using crawly recently and I found the folder option a bit confusing. 

The folder is always set as `/tmp` which makes think that only absolute paths are allowed. A single example with a local or `~` path would make things clearer, for example here in the last one: https://hexdocs.pm/crawly/Crawly.Pipelines.WriteToFile.html

The other thing that bugs me is that the folder has to exist. It would be nicer if the folder is created when missing. This would open the possibility of setting the default to a local path, making it more immediate whether the parser is working

**Comment by Ziinc** [comment]
It actually defaults to the current folder.

Documentation should be fixed

**Comment by Ziinc** [comment]
And the folder option is optional, it doesn't always need to be declared.

**Comment by oltarasenko** [comment]
Released
