### ISSUE TITLE
Improvements to output file names of spiders

### ISSUE THREAD

**Issue by Vesuvium** [oltarasenko/crawly#92]
Right now the file name is the spider's module name and there's no way to configure it. Because the file name is static, previous data is overwritten, where as scrapers usually add a timestamp to the file name. That would be very nice because in this way previous results are automatically retained and it's immediate when the parsing was done.

Spiders could have an optional `name` method which could be used to enable users to customize it and the default naming could include a timestamp.

**Comment by oltarasenko** [comment]
A good thing to do. We will include it to the roadmap!

**Comment by oltarasenko** [comment]
This is now merged to master branch. @Vesuvium it will be included in the 0.10.0 release which will happen tomorrow.

**Comment by oltarasenko** [comment]
Released
