### ISSUE TITLE
WriteFile produces invalid json

### ISSUE THREAD

**Issue by Vesuvium** [oltarasenko/crawly#93]
When writing json, WriteFile produces invalid json, as it uses a newline to separate items.

```json
{"title": "first item}
{"title": "second item"}
```

The items should be in a list, comma separated:
```json
[
    {"title": "first item"},
    {"title": "second item"}
]
```

**Comment by oltarasenko** [comment]
Well it produces JSON lines not JSON. See also https://hackernoon.com/json-lines-format-76353b4e588d

**Comment by oltarasenko** [comment]
@Vesuvium I plan to close this ticket if you don't have other comments

**Comment by Vesuvium** [comment]
Ah right, thanks for the explanation. Yes, it can be closed.
